"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](fg:red)\
$os\
$username\
[î‚°](bg:peach fg:red)\
$directory\
[î‚°](bg:yellow fg:peach)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[î‚°](bg:blue fg:yellow)\
$jobs\
[î‚°](bg:lavender fg:blue)\
$shell\
[î‚´ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
format = '[$symbol]($style)'
style = "bg:red fg:crust"

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ó°£‡ "
CentOS = "ïŒ„ "
Debian = "ó°£š "
EndeavourOS = "ó°£‡ "
Fedora = "ó°£› "
Gentoo = "ó°£¨ "
Linux = "ó°Œ½ "
Macos = "ó°€µ "
Manjaro = "ïŒ’ "
Mint = "ó°£­ "
Raspbian = "ó°¿ "
RedHatEnterprise = "ó±„› "
Redhat = "ó±„› "
SUSE = "ïŒ” "
Ubuntu = "ó°•ˆ "
Windows = "îœ "

[username]
format = '[ $user ]($style)'
style_root = "bg:red fg:crust"
style_user = "bg:red fg:crust"

[directory]
before_repo_root_style = "bg:peach fg:crust"
format = "[ $path ]($style)"
repo_root_format = """
[ $before_root_path]($before_repo_root_style)\
[$repo_root ó°Š¢ ]($repo_root_style)\
[$path ]($style)"""
repo_root_style = "bg:peach fg:crust"
style = "bg:peach fg:crust"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"~/Code" = "~/ó°²‹ "
"~/Documents" = "~/ó°ˆ™ "
"~/Downloads" = "~/ï€™ "
"~/Music" = "~/ó°š "
"~/Pictures" = "~/ï€¾ "

[git_branch]
format = '[ $symbol$branch ]($style)'
only_attached = true
style = "bg:yellow fg:crust"
symbol = "ó°˜¬ "

[git_commit]
format = '[ (ó°œ˜ $hash )($tag )]($style)'
style = "bg:yellow fg:crust"
tag_disabled = false
tag_max_candidates = 100
tag_symbol = "ğŸ· "

[git_state]
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
style = 'bold bg:yellow fg:crust'

[git_metrics]
added_style = "bg:yellow fg:crust"
deleted_style = "bg:yellow fg:crust"
disabled = false
format = """
[\
([ï‘— $added]($added_style) )\
([ï‘˜ $deleted]($deleted_style) )\
](bg:yellow fg:crust)"""

[git_status]
ahead = "ï¢ $count"
behind = "ï£ $count"
conflicted = "ğŸ’$count"
deleted = "âœ˜ $count"
diverged = "ï½ ï¢ $ahead_count ï£ $behind_count"
format = '[($all_status$ahead_behind$ahead_count$behind_count$count )]($style)'
modified = "ï‘™ $count"
renamed = "ï‘š $count"
staged = "ï† $count"
stashed = 'ó±£« $count'
style = "bg:yellow fg:crust"
typechanged = ""
untracked = "ï„¨ $count"
up_to_date = ""

[jobs]
format = '[ $symbol( $number) ]($style)'
style = "bg:blue fg:crust"

[shell]
bash_indicator = "ó±†ƒ"
cmd_indicator = "î¯„ "
disabled = false
fish_indicator = "î¹ "
format = '[ $indicator]($style)'
nu_indicator = "ï”"
powershell_indicator = "î¯‡ "
pwsh_indicator = "ó°¨Š "
style = "fg:crust bg:lavender"

[line_break]
disabled = true

[character]
error_symbol = '[â¯](bold fg:red)'
success_symbol = '[â¯](bold fg:green)'
vimcmd_replace_one_symbol = '[â®](bold fg:lavender)'
vimcmd_replace_symbol = '[â®](bold fg:lavender)'
vimcmd_symbol = '[â®](bold fg:green)'
vimcmd_visual_symbol = '[â®](bold fg:yellow)'

[cmd_duration]
format = "î«´ in $duration "
min_time_to_notify = 45000
show_milliseconds = true
show_notifications = true
style = "bg:lavender"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
